---
title: "kruskal-wallis"
author: "Clara Wong"
date: "2023-04-27"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(PMCMRplus)
library(modelr)
```

## Data
Weiss and Martindale S1 Database
```{r}
database <- readxl::read_xls("S1 Database.xls")
```

## Dweller Test
```{r kruskal-wallis}
kruskal.test(x = database$Dweller_diversity, g = database$Algae_score)
```

```{r nemenyi}
kwAllPairsNemenyiTest(x = database$Dweller_diversity, g = database$Algae_score)
```

```{r}
datakw <- matrix(nrow = 1000, ncol = 3)
database2 <- database %>%
  mutate(index = 1:nrow(database))

for (i in 1:1000) {
 resampled_id <- sample(database2$index, size = 100, replace = FALSE)
 resampled_data <- database2 %>%
   filter(index %in% resampled_id)
 kw <- kruskal.test(x = resampled_data$Dweller_diversity, g = resampled_data$Algae_score)
 datakw[i,1] <- kw$statistic
 datakw[i,2] <- kw$parameter
 datakw[i,3] <- kw$p.value
}
colnames(datakw) <- c("Kruskal-Wallis_Chi_Squared", "df", "p-value")
```
